//! Pure domain layer. No IO, no async, no infra imports.
pub mod alert;
pub mod asset;
pub mod candle;
pub mod fx;
pub mod holding;
pub mod indicators;
pub mod money;
pub mod percent;
pub mod portfolio;
pub mod portfolio_calc;
pub mod price;
pub mod prompt;
pub mod quantity;
pub mod quote;
pub mod sanity;
pub mod symbol;
pub mod time_range;
pub mod watchlist;
